apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nbastatic
  labels:
    app: nbaappfrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nbaappfrontend
  template:
    metadata:
      labels:
        app: nbaappfrontend
    spec:
      containers:
      - name: nbastats1
        image: nbastats.azurecr.io/nbaappfrontend:latest
        ports:
        - containerPort: 3000
        # env:
        #   - name: PASSWORD
        #     value: 'Preston123avinash'
        #   - name: DB
        #     value: 'NbaStats'
        #   - name: HOST
        #     value: 'nbastats.database.windows.net'
        #   - name: USER
        #     value: 'user'
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: azure-load-balancer
# spec:
#   loadBalancerIP: 40.87.92.80
#   type: LoadBalancer
#   ports:
#   - port: 80
#   selector:
#     app: azure-load-balancer
